language: php

php:
  - '7.4'

env:
  - CODECOV_TOKEN="845407a7-add8-45a2-91d5-d4cc94184e53"

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - ./vendor/phpunit/phpunit/phpunit --coverage-html docs/tests/
  - ./vendor/phpunit/phpunit/phpunit --coverage-text --coverage-clover=coverage.clover

after_success:
  - bash <(curl -s https://codecov.io/bash)


